C******************** START FILE NUMFLD.FOR ; GROUP URDUTS *************
C------------------------------
C&   NUMFLD  OLD UREAD - NUMERIC FIELD LIMITS, UNPACKED LINE BUFFER
C
C   INDENTIFY LIMITS OF A NUMERIC FIELD
C  COMMAS AND BLANKS ARE LEGIT DELIMITTERS
C
      SUBROUTINE NUMFLD(DBUFF,NID1,NID2,NUM)
C
      implicit NONE
C
      integer NID1,NID2,NUM
      CHARACTER*1 DBUFF(512),MCOMMA
C
      integer i
C
      DATA MCOMMA/','/
C
C  FIND BLANK-DELIMITTERS
C
      CALL FLDLIM(DBUFF,NID1,NID2,NUM)
      IF(NUM.EQ.0) RETURN
C  CHECK FOR COMMAS
      DO 10 I=NID1,NID2
      IF(DBUFF(I).NE.MCOMMA) GO TO 12
 10   CONTINUE
      NUM=0
      NID2=NID1
      RETURN
C
 12   CONTINUE
      NID1=I
      DO 20 I=NID1,NID2
      IF(DBUFF(I).EQ.MCOMMA) GO TO 22
 20   CONTINUE
C  NO COMMAS
      GO TO 30
 22   CONTINUE
      NID2=I-1
 30   CONTINUE
      NUM=NID2-NID1+1
      RETURN
      END
C******************** END FILE NUMFLD.FOR ; GROUP URDUTS ***************
