C******************** START FILE FILFCN.FOR ; GROUP FILTR0 ******************
C------------------------------------------------------------
C  FILFCN
C
C  COMPUTE WEIGHTED AVERAGE ABOUT PT X(J0).
C
C  END CONDITIONS:
C     IEND?=0==> FIX END PT. OF REGION BEING SMOOTHED.
C                THE DATA CURVE IS REFLECTED ABOUT THE PT.
C                [X(1),Y(1)] ( OR [X(N),Y(N)])
C               SO THAT BY SYMMETRY OF THE WEIGHTING
C                FUNCTION ==> THE END PTS ARE FIXED
C
C      IEND?=1==> DON'T FIX END PT. OF REGION. END PT
C                IS RESET TO WEIGHTED AVERAGE OF NEARBY PTS.
C                THE DATA IS REFLECTED ABOUT THE LINE X=X(1)
C                FOR THE LEFT END, ABOUT THE LINE X=X(N)
C                FOR  THE RIGHT END.
C
C
C---------------------------------------------
C
      REAL FUNCTION FILFCN(X,Y,N,J0,DELTA0,IEND1,IEND2)
C
      DIMENSION X(N),Y(N)
C
C  START OF EXECUTABLE CODE --
C
      DDFAC=1.0
C
      FILFCN=Y(J0)
      IF((J0.EQ.1).AND.(IEND1.EQ.0)) RETURN
      IF((J0.EQ.N).AND.(IEND2.EQ.0)) RETURN
C
      DELTA=DDFAC*DELTA0
      FILFCN=Y(J0)
      IF(DELTA.LE.0.) RETURN
      IF(DELTA.GT.(X(N)-X(1))) DELTA=X(N)-X(1)
C
C  EVALUATE DENOMINATOR OF WEIGHTED AVERAGE FORMULA
C
      XLIM1=X(J0)-DELTA
      XLIM2=X(J0)+DELTA
COLD	IF((IEND1.EQ.1).AND.(XLIM1.LT.X(1))) XLIM1=X(1)
COLD	IF((IEND2.EQ.1).AND.(XLIM2.GT.X(N))) XLIM2=X(N)
C
      DENOM=WXCINT(XLIM1,XLIM2,1.,X(J0),DELTA)
C
C  EVALUATE NUMERATOR OF WGTED. AVG.
C
C  (A) PTS TO THE LEFT OF X(J0)
C
      WASUM=0.
C
      J=J0
      XA=X(J0)
      YA=Y(J0)
 10   J=J-1
COLD	IF((IEND1.EQ.1).AND.(J.LT.1)) GO TO 50
      XB=XA
      YB=YA
      IF (J) 11,11,12
C
C  REFLECT PTS ABOUT X(1),Y(1)
C
C
 11   CONTINUE
      JR=2-J
      IF(((X(J0)-XB).GE.DELTA).OR.(JR.GT.N)) GO TO 50
      XA=X(1)-(X(JR)-X(1))
      IF(IEND1.EQ.0) YA=Y(1)-(Y(JR)-Y(1))
      IF(IEND1.EQ.1) YA=Y(JR)
      GO TO 15
C
 12   CONTINUE
      IF((X(J0)-XB).GE.DELTA) GO TO 50
      XA=X(J)
      YA=Y(J)
C
C  COMPUTE WEIGHTED AVERAGE INTEGRAL FROM XA1 TO XB
C
 15   CONTINUE
      XA1=AMAX1(XA,(X(J0)-DELTA))
      WASUM=WASUM+WXFINT(XA1,XB,XA,YA,XB,YB,X(J0),DELTA)
C
      GO TO 10
C
C (B) COMPUTE CONTRIBUTION OF DATA TO RIGHT OF X(J0)
C
 50   CONTINUE
C
      J=J0-1
      XB=X(J0)
      YB=Y(J0)
 60   J=J+1
COLD	IF((IEND2.EQ.1).AND.((J+1).GT.N)) GO TO 100
      XA=XB
      YA=YB
      IF(N-J) 61,61,62
C
C  REFLECT ABOUT X(N),Y(N)
C
 61   CONTINUE
      JR=N+N-J-1
      IF(((XA-X(J0)).GE.DELTA).OR.(JR.LT.1)) GO TO 100
      XB=X(N)+(X(N)-X(JR))
      IF(IEND2.EQ.0) YB=Y(N)+(Y(N)-Y(JR))
      IF(IEND2.EQ.1) YB=Y(JR)
      GO TO 65
C
 62   CONTINUE
      IF((XA-X(J0)).GE.DELTA) GO TO 100
      XB=X(J+1)
      YB=Y(J+1)
C
C  INTEGRATE FROM XA TO XB1
C
 65   XB1=AMIN1(XB,(X(J0)+DELTA))
C
      WASUM=WASUM+WXFINT(XA,XB1,XA,YA,XB,YB,X(J0),DELTA)
C
      GO TO 60
C
C
C  RETURN COMPUTED WEIGHTED AVERAGE
C
 100  CONTINUE
C
      FILFCN=WASUM/DENOM
C
      RETURN
      	END
C******************** END FILE FILFCN.FOR ; GROUP FILTR0 ******************
