C******************** START FILE WXCINT.FOR ; GROUP FILTR6 ******************
C==========================================================
C
C  WXCINT
C
C  COMPUTE C*INTEGRAL OF WEIGHTING FUNCTION FROM X1 TO X2
C
C  DENOMINATOR IN WEIGHTED AVERAGE FORMULA
C
C  W(T)=1-ABS((XCEN-T)/DELTA)   XCEN-DELTA .LE. T .LE. XCEN+DELTA
C
C  TRIANGULAR SHAPED WEIGHTING FUNCTION CENTERED AT XCEN
C    X1 SHOULD BE .LT. X2 AND X1 AND X2 SHOULD
C    BE WITHIN DELTA OF XCEN
C-------------
      REAL FUNCTION WXCINT(X1,X2,C,XCEN,DELTA)
C
      WXCINT=C
      XA=AMAX1(-DELTA,(X1-XCEN))
      XB=AMIN1(DELTA,(X2-XCEN))
      IF((XA.GT.DELTA).OR.(XB.LT.-DELTA)) GO TO 1000
      IF(XB.LT.XA) GO TO 1000
C
C  NUMERICS CHECK; DELTA <<< X1
      IF(XCEN.EQ.(XCEN+DELTA)) RETURN
C
      ZDI=1./DELTA
      IF((XA.GT.0.).OR.(XB.LT.0.)) GO TO 100
C
      WXCINT=C*ZDI*((XB-XA)-.5*(XA*XA+XB*XB)*ZDI)
      RETURN
C
 100  CONTINUE
      IF(XA.GT.0.) WXCINT=C*ZDI*((XB-XA)-.5*(XA+XB)*(XB-XA)*ZDI)
      IF(XB.LT.0.) WXCINT=C*ZDI*((XB-XA)-.5*(XA+XB)*(XA-XB)*ZDI)
      RETURN
C
 1000 CONTINUE
      write(6,9000)
 9000 FORMAT(' SUBROUTINE WXCINT FROM FILFN6 FROM FILTR6.FOR:'/
     >         ' ILLEGAL INTEGRATION LIMITS')
      call bad_exit
      	END
C******************** END FILE WXCINT.FOR ; GROUP FILTR6 ******************
