C******************** START FILE WXFINT.FOR ; GROUP FILTR6 ******************
C---------------------------------------------------------------
C   WXFINT
 
C
C  COMPUTES INTEGRAL OF W(T)*F(T)*DT
C   WHERE W(T)=1-ABS(XCEN-T)/DELTA IS THE WEIGHTING FUNCTION
C   AND F(T) IS THE PIECEWISE LINEAR INTERPOLATION FUCNTION
C   OF THE DATA SERIES.
C
C   INTEGRATE FROM X1 TO X2
C   (XF1,YF1),(XF2,YF2) ARE THE ENDPOINTS OF A LINEAR
C   SEGMENT OF F(T);  XCEN SHOULD NOT LIE BETWEEN XF1 AND
C   XF2, X1 AND X2 SHOULD EQUAL OR LIE
C   BETWEEN XF1 AND XF2
C
      REAL FUNCTION WXFINT(X1,X2,XF1,YF1,XF2,YF2,XCEN,DELTA)
C
      ZS=(YF2-YF1)/(XF2-XF1)
      XA=AMAX1((X1-XCEN),-DELTA)
      XB=AMIN1((X2-XCEN),DELTA)
      XFA=XF1-XCEN
C
      ZC0=YF1-XFA*ZS
      ZDI=1./DELTA
      ISIGN=-1
      IF(XA.LT.0.) ISIGN=1
      ZC1=.5*(ZS+ISIGN*ZC0*ZDI)
      ZC2=.3333333333333333333333333*ISIGN*ZS*ZDI
C
      WXFINT=ZDI*(XB-XA)*(ZC0+
     >           (XB+XA)*ZC1
     >          +(XB*XB+XA*XB+XA*XA)*ZC2)
C
      RETURN
      	END
C******************** END FILE WXFINT.FOR ; GROUP FILTR6 ******************
